### ISSUE TITLE
index.html not placed on root after build on windows

### ISSUE THREAD

**Issue by ullumullu** [Snugug/gulp-armadillo#128]
After the gulp build chain the index.html file is always copied into /index/index.html instead of placing it dorectly in the root. This only happens on windows. I've already created a merge request with a possible fix: #127

**Comment by Snugug** [comment]
Thanks for filing this issue. It's going to be fixed in the [3.x](https://github.com/Snugug/gulp-armadillo/tree/3.x) release of Armadillo. See https://github.com/Snugug/gulp-armadillo/blob/3.x/lib/plugins/path-transform.js#L25-L27

**Comment by Snugug** [comment]
Resolved with https://github.com/Snugug/gulp-armadillo/pull/197
