### ISSUE TITLE
Bug: Folder list needs correction for documents folder 

### ISSUE THREAD

**Issue by kellychurchill** [Snugug/gulp-armadillo#208]
Folder list needs correcting for "documents" folder

## Steps for Reproducing

- add files to the documents folder
- build
- verify documents folder was not successfully copied

## Code Version

3.6.0

**Comment by Snugug** [comment]
This was a bug in the Yeoman generator. You can change that via your project's settings or by renaming your documents folder. This was resolved in the generator https://github.com/Snugug/generator-armadillo/commit/d604d49033469c327d44e723158ebd3fca835d42
