### ISSUE TITLE
Feature request: Support multimedia embedding for Ustream videos

### ISSUE THREAD

**Issue by kellychurchill** [Snugug/gulp-armadillo#209]
Gulp armadillo supports multimedia embedding for Youtube and Vimeo. As a Ustream account user, I would like to be able to embed videos already hosted on Ustream.

```gherkin
Feature: Support for Ustream videos
  As a user
  I want to embed videos from Ustream
  So that I can utilize the Ustream service for video content management

  Scenario: Support Ustream video embedding 
    Given markdown content
     When embedding a video from Ustream using the video embed feature
     Then serve the Ustream video embedded in the rendered page
```

---

**FEATURE**
- [ ] Support Ustream video embedding

**Comment by Snugug** [comment]
Sounds good to me! If you'd like to submit a PR happy to take a look! Will be under the render function of the markdown video plugin in helpers
