### ISSUE TITLE
Bug: custom gulp-gh-pages options aren't working

### ISSUE THREAD

**Issue by tteltrab** [Snugug/gulp-armadillo#225]
The publish configuration isn't correctly being passed to the gulp-gh-pages plugin (see [deploy.js line 11](https://github.com/Snugug/gulp-armadillo/blob/master/tasks/deploy.js#L11)). There's a typo - should be `config.publish`. As a result, the automated publishing isn't quite working as expected (with the custom message), and overriding that configuration doesn't behave as expected.

## Steps for Reproducing

1. Run `gulp deploy` locally.
2. Go take a look at what was deployed.

## Screenshots

The files are deployed without the expected commit message:
![files deployed without expected commit message](https://cloud.githubusercontent.com/assets/1487463/23011006/6f057804-f3ec-11e6-9dc4-a6492eace05f.png)

## Code Version

[4.2.0](https://github.com/Snugug/gulp-armadillo/releases/tag/v4.2.0)

**Comment by Snugug** [comment]
This seems straight forward enough of a bug to fix, feel free to open a PR to do so!

**Comment by kellychurchill** [comment]
Hey @tteltrab! 

I ran into this horrendous blocking issue too. I just created a PR for it 😄
